### ISSUE TITLE
Can't resolve 'babel'

### ISSUE THREAD

**Issue by davidfloegel** [CrocoDillon/universal-react-redux-boilerplate#14]
Hey,

I wanted to try out your boilerplate but I keep getting:

`Module not found: Error: Can't resolve 'babel' in ...`

Do you have any idea how to fix this?

Thanks!

**Comment by mohamedfasil** [comment]
Try installing babel globally,

**Comment by mohamedfasil** [comment]
Sorry looks like breaking changes from webpack, update the loaders in webpack config with '-loader' prefix

**Comment by CrocoDillon** [comment]
Oh yeah I figured that out on a project that uses this boilerplate but didn't merge the changes back in. Will do asap!

Thanks for reminding me 😄

**Comment by CrocoDillon** [comment]
Updated dependencies (on master) which includes some fixes for errors like this one.
