### ISSUE TITLE
Syntax question on Blog.js

### ISSUE THREAD

**Issue by sk25649** [CrocoDillon/universal-react-redux-boilerplate#17]
How is Blog component is a function instead of a React class? and also able to do `Blog.onEnter(..)` on a function?

If you could answer this, that will be so helpful.

**Comment by CrocoDillon** [comment]
If you don't need state you can use functions to define a [(stateless) component](https://facebook.github.io/react/docs/components-and-props.html).

Functions are objects so you can add properties to them like `Blog.onEnter` just like on any other object. It works just the same as static properties on classes.

Is there anything still unclear?

**Comment by sk25649** [comment]
cool. thank you for your answer!
