### ISSUE TITLE
By far the best react-redux boilerplate. Update deps?

### ISSUE THREAD

**Issue by rolele** [CrocoDillon/universal-react-redux-boilerplate#21]
Thanks for your work, I like this boilerplate.
Because you are comfortable with this project and because the last update was 5 month ago, would you mind updating to a more recent version of webpack for instance?

I am also wondering if the PR https://github.com/CrocoDillon/universal-react-redux-boilerplate/pull/19 is worth merging or not.

Thanks

**Comment by CrocoDillon** [comment]
Thanks for the motivating words 😄 It sure helped getting #19 merged and pushing a commit updating dependencies, see d7a5a2d1d2aeb09f765de4e30b0b537c087504ef.

Only thing I haven't done yet is updating to React Router v4.

**Comment by rolele** [comment]
excellent work thanks. I am actually experimenting with this boilerplate and I think it is great.

**Comment by CrocoDillon** [comment]
Awesome! You happen to have any idea why the build fails?

**Comment by rolele** [comment]
sorry for the late reply.
I just checked out master and run the check command on a fresh build and everything is working fine.
I am using node 7.10.0

**Comment by rolele** [comment]
I see that on you CI, you are using:
```
node --version
v5.12.0
$ npm --version
3.8.6
$ nvm --version
0.33.2
```
maybe that is the problem

**Comment by rolele** [comment]
Yeah that is the problem.
I installed node 5.12.0 using the command: `nvm install 5`
and I get an error while running `npm run check`
Maybe the only thing you have to do is change the .travis to
```
node_js:
- 7
```
also I like to add this to my package.json so I am sure that on every machine I am running the code I know that the right node version is used (optional)
```
  "engineStrict" : true,
  "engines": {
    "node": "7.10.0"
  }
```

**Comment by CrocoDillon** [comment]
Thanks! That's an easy fix, I'll try it tomorrow 😄
