### ISSUE TITLE
Figure out why the build is failing

### ISSUE THREAD

**Issue by CrocoDillon** [CrocoDillon/universal-react-redux-boilerplate#22]
Build is failing on CI, while it's not locally... 😢

**Comment by islam3zzat** [comment]
I'm also stuck in [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
then getting  Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
when trying to deploy on heroku

**Comment by brijesh-pant** [comment]
@islam3zzat the error you are facing may not be of webpack bundling.
You need to update the port number at 
https://github.com/CrocoDillon/universal-react-redux-boilerplate/blob/master/bin/server#L28
to something like this
https://github.com/brijesh-pant/universal-react-starter/blob/develop/bin/server.js#L10

Hope that helps!

**Comment by CrocoDillon** [comment]
For this issue, the solution is [here](https://github.com/CrocoDillon/universal-react-redux-boilerplate/issues/21#issuecomment-301306333).

I'll implement it later this week.
