### ISSUE TITLE
Update to RRv4

### ISSUE THREAD

**Issue by CrocoDillon** [CrocoDillon/universal-react-redux-boilerplate#23]
While I like the API of RRv3 more, it's time to update to v4. I will probably write some wrapper because I don't like to have route configuration all over the place. It has to be either in one place, or at least very well structured.

**Comment by rolele** [comment]
Excellent I was looking at RRv4 doc and it says that the on* callback are now deprecated.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md#on-properties
I think this boilerplate rely on the onEnter callback to perform server rendering.
What is the best way to do server rendering in that case ?

**Comment by CrocoDillon** [comment]
Exactly, I think the same is possible with [`react-router-config`](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config), but I just haven't had the time to try it out yet.

**Comment by rolele** [comment]
I think this react router config lib is too experimental. I might try to use this as an example https://github.com/technology-ebay-de/universal-react-router4 and apply it to the boilerplate.

**Comment by rolele** [comment]
I am working on that one. the client side is fine for now but I am having some trouble with the server-side. I will keep working on a solution. hopefully I will have a PR soon. 
Have you done any progress on this one?

**Comment by CrocoDillon** [comment]
Not yet, looking forward to see what you come up with!

**Comment by dlucidone** [comment]
@rolele @CrocoDillon any idea when can we have RR4 on this boilerplate

**Comment by CrocoDillon** [comment]
I'll make sure to find some time to update to RRv4 next weekend. There is an open PR for it but it needs some more work.

**Comment by CrocoDillon** [comment]
Okay didn't happen in the weekend. I'll do my best though to do this soon.

**Comment by CrocoDillon** [comment]
Finally done, there is an (unrelated) issue with hot reloading though... see #30
