### ISSUE TITLE
Server-side Data Fetching

### ISSUE THREAD

**Issue by maheshambiga** [CrocoDillon/universal-react-redux-boilerplate#24]
I don't see any code to fetch data in server-side before sending response back to the browsers. It means that one should be able to make an API call and use its response as data to generate html using react.

**Comment by CrocoDillon** [comment]
The code to do server side fetching is in [`routes.js`](https://github.com/CrocoDillon/universal-react-redux-boilerplate/blob/6427383f187629af101c8051144576db3a85271c/src/routes.js#L39).

Not sure what you mean by the second sentence.
