### ISSUE TITLE
Preload data on non-routes component

### ISSUE THREAD

**Issue by devmarwen** [CrocoDillon/universal-react-redux-boilerplate#26]
First thanks for the awesome work :100: 
I saw that you used an `onEnter` hook to fetch data on components that are used as pages/routes.

What if we wanted to fetch data on non pages/routes components, how to change this bit of code to achieve that:

```javascript
// On server we want to fetch all data for the current route before rendering
const fetchData = store => (nextState, replace, callback) => {
  Promise.all(
    nextState.routes.map(route => {
      if (route.component.onEnter) {
        return route.component.onEnter(store, nextState)
      }
    })
  ).then(() => callback())
}
```

Thanks!

**Comment by CrocoDillon** [comment]
That's tricky, with React Router and co you only get the matching routes... not their descendants.

Can't you change your component tree and put the components that need data in the route config? (which just updated to RRv4 btw, so expect some changes)
