### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by anorudes** [CrocoDillon/universal-react-redux-boilerplate#3]
nice work, @CrocoDillon . Your boilerplate is very pretty. Please, don't leave him )

**Comment by CrocoDillon** [comment]
Hehe, thanks! No worries, I’m working on version 2 but it takes some time (which I don’t have a lot at the moment) :smile:

**Comment by CrocoDillon** [comment]
Just wanted to let you know I'm actively working on [v2](https://github.com/CrocoDillon/universal-react-redux-boilerplate/tree/v2) now which will include Koa 2, React 15, React Hot Loader 3, Webpack 2, linting, testing and static type checking... it will be good! Will be finished in a week or two, I hope.

Also noticed the [package quality](http://packagequality.com/#?package=universal-react-redux-boilerplate) of this boilerplate absolutely sucks! So will need to close down issues faster to get that up. Closing this one too.
