### ISSUE TITLE
How to add external script

### ISSUE THREAD

**Issue by newkolay** [CrocoDillon/universal-react-redux-boilerplate#33]
Hello, first of all, great boilerplate. I could finally set server rendering with this code. The only problem i have is to add external scripts (google analytics, fb pixel, mixpanel, etc.) 
I've tried add it to Html.js but got error  'Unexpected token'. Any help please? Thank you

**Comment by CrocoDillon** [comment]
You probably either need to use [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) or add the script contents as a string (didn't test it though)... e.g.

```js
<script>{`
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
  (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  ga('create', 'UA-XXXXXXXXX-X', 'example.com');
  ga('send', 'pageview');
`}</script>
```
