### ISSUE TITLE
trouble importing absolute paths

### ISSUE THREAD

**Issue by pailhead** [CrocoDillon/universal-react-redux-boilerplate#34]
I cant import absolute paths with this kit 

`import foo from /components/foo`

I've tried a few different things in `webpack.config` but couldnt get anything to work. Any examples?

**Comment by CrocoDillon** [comment]
Haven't really looked into this but first thing that comes to mind is that for SSR this boilerplate doesn't use Webpack, only Babel. You might need a Babel plugin in addition to configuring Webpack.

**Comment by pailhead** [comment]
Thanks for the reply and hint! Out of many boilerplates i settled on this one for studying, really appreciate the work!

**Comment by CrocoDillon** [comment]
No problem! I'm happy to hear that 😄 Let me know if/when you worked it out, otherwise I'll look into it when I have time.

**Comment by pailhead** [comment]
Solved this with https://www.npmjs.com/package/babel-plugin-module-resolver

But now i'm struggling with images and file-loader :(

**Comment by pailhead** [comment]
... which were fixed with yet another babel plugin `transform-assets`. I'm still not sure if i have a good grasp of what is going on, i expected the `webpack-isomorphic-tools` to be able to handle this since it's doing it  with sass? But i couldnt get it to work.

**Comment by pailhead** [comment]
It seems that i was a bit behind, when upgrading to the latest version of the repo `transform-assets` doesnt seem to be working. Paths do seem like they are resolved properly when trying absolute, but i get 404s when trying to load them. I don't really understand what is happening.

For example

//src/modules/someComponent/someStyle.scss

```
.someClass{
  background-image:  url('/static/someImage.jpg'); //works, but 404 on loading (webpack doesnt complain)
  background-image: url('./static/someFoo.jpg'); //doesnt work because nothing at that path
  background-image: url('../../static/someImage.jpg'); //works because correct path
}
```

Seems to me the only change between where i could get this to work and now is the router upgrade, could it somehow be getting in the way?
