### ISSUE TITLE
how is server side css supposed to work?

### ISSUE THREAD

**Issue by pailhead** [CrocoDillon/universal-react-redux-boilerplate#36]
I realized that my issue with server side rendering might be the separate css file. I purposely made imported entire font awesome to play with the paths and see in general how it performs.

I see now that in development it inlines all of the apps css on the server, while the same loader passes through `ExtractTextPlugin` in production? 

I'm not sure if I understand how this is supposed to work. Googling got me the term `critical path rendering`, which sounds like what imagined should happen with this client/server optimization. What does this boilerplate do in terms of that? 

If I remove the `ExtractTextPlugin` in production, it will inline the entire css bundle, not just the styles for the requested page?

**Comment by CrocoDillon** [comment]
Yeah it will probably inline the entire CSS bundle, though I haven't tried that. The `ExtractTextPlugin` is to put all that in a separate CSS file for caching. It's not really about the critical path, it's just easier in development to inline everything.

**Comment by pailhead** [comment]
Would this make sense to add to this boilerplate?

https://github.com/kriasoft/isomorphic-style-loader

I see at a minimum that it would be more verbose with HOC. I could live with that, but when i saw the HMR setup and all, i panicked 🤕 
I'm going to give it a shot, but was wondering what expert opinion is :D
