### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wayspurrchen** [CrocoDillon/universal-react-redux-boilerplate#4]
Hi, this is an awesome boilerplate that's the cleanest I've seen with all the features I want. I'm interested in using some portions of it, but I'd like to know how this is licensed first.

**Comment by CrocoDillon** [comment]
Sorry for getting back so late, was not getting notifications for this repo :/ If it still matters I guess I would say public domain. There is nothing of me in there really, just putting other people's stuff together ;)

Will update package.json and add a license file soon to make that clear. Got any suggestions for a valid public domain license?

**Comment by CrocoDillon** [comment]
Listed license is now Creative Commons Zero (Public Domain). In v2 I also added a LICENSE.md file to make it more obvious than just list it in package.json.

**Comment by wayspurrchen** [comment]
@CrocoDillon Awesome, thank you! :)
