### ISSUE TITLE
Minimum universal react API

### ISSUE THREAD

**Issue by guidsen** [CrocoDillon/universal-react-redux-boilerplate#5]
Hi, I've been working on https://github.com/guidsen/react-simple-universal that solved the boilerplate involved with universal React Apps.

I'm really curious about your thoughts about this and would love to have some help evolving this repo.

**Comment by CrocoDillon** [comment]
You’re asking the wrong guy (assuming this is not a shameless plug :stuck_out_tongue_winking_eye: )... I like setting up the boilerplate at the start of my projects. Gives me insight in how things work.

Open sourcing my boilerplate will hopefully help others but at least it helps me if no one else.

That said, I’m sure there are people that like the boilerplate less and will enjoy working higher level tools like yours. So keep up the good work!

And come back in a week or two as I’m working actively on [v2](https://github.com/CrocoDillon/universal-react-redux-boilerplate/tree/v2) now :wink:
