### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by bgies** [CrocoDillon/universal-react-redux-boilerplate#6]
Just thought I'd let you know that I like what you've done... your readme makes a lot more sense to me than most boilerplate, and I like that you haven't included everything but the kitchen sink, and forced anyone using your boilerplate to use your coding style :) 

FYI... when I ran npm run dev I get errors (I'm on Windows if that matters).... the error is in the .bin/server.js file at line 4 const basePath = path.resolve(__dirname, __DEV__ ? '../src' : '../lib')

At that point __DEV__ is not defined.

Where should it be defined? I fixed it temporarily by adding this above it : const __DEV__ = true;
But that's obviously not a good way.

Should I be editing the globals.js file? If so, can you add that to the readme?

**Comment by CrocoDillon** [comment]
Thanks for the heads up! It's fixed now and I added some other fixes for Windows (this issue was not platform specific though, just me messing the order of things up). I rebased the master branch :walking: so keep that in mind when pulling the latest changes.
