### ISSUE TITLE
Node version limitation?

### ISSUE THREAD

**Issue by saniko** [CrocoDillon/universal-react-redux-boilerplate#7]
Hi,
Any node version limitation?, cannot run the app.

**Comment by CrocoDillon** [comment]
Hey, this has most likely to do with the Babel presets. I'm using [`babel-preset-es2015-node5`](https://www.npmjs.com/package/babel-preset-es2015-node5) which requires Node 5+.

If you're running Node 4 or lower you might need [`babel-preset-es2015`](https://www.npmjs.com/package/babel-preset-es2015). Install it as dev dependency and change this line in [`.babelrc#L2`](https://github.com/CrocoDillon/universal-react-redux-boilerplate/blob/master/.babelrc#L2).

**Comment by saniko** [comment]
tried with node 5 and 6..

Sent from Yahoo Mail on Android 

  On יום ד׳, יולי 27, 2016 at 21:05, Dillon de Voornotifications@github.com wrote:  
Hey, this has most likely to do with the Babel presets. I'm using babel-preset-es2015-node5 which requires Node 5+.

If you're running Node 4 or lower you might need babel-preset-es2015. Install it as dev dependency and change this line in .babelrc#L2.

**Comment by CrocoDillon** [comment]
What are you trying to do and what error do you get exactly?
