### ISSUE TITLE
No redux?

### ISSUE THREAD

**Issue by BlueAccords** [CrocoDillon/universal-react-redux-boilerplate#9]
So i was browsing your boilerplate and checking out the `package.json` since the src didn't seem to include redux anywhere and it isn't set as a dependency in `package.json`.

Are you planning on adding it in later or something or was it intended for it not to be included?

**Comment by CrocoDillon** [comment]
I am planning on adding it later. In fact, it will be the next commit and I have some work in progress but I'm not yet 100% happy with it.

Sorry it's taking me longer than I hoped, if you need some inspiration right now you can check out the [`v1` branch](https://github.com/CrocoDillon/universal-react-redux-boilerplate/tree/v1) which includes the previous Redux commit.

**Comment by BlueAccords** [comment]
Alright, thanks for the suggestion. Did you have a rough timeline of when the next commit will be done?

**Comment by CrocoDillon** [comment]
Hopefully next weekend, I'll do my best! :smile:

**Comment by CrocoDillon** [comment]
Sorry for the delay! But I can finally mark this as **done**.

Not sure if I am actually 100% happy with the results but w/e, right? :shipit:
